import { environment } from '../../../environments/environment';

const base = environment.apiBaseUrl;

export const ApiEndpoints = {
  auth: {
    register: `${base}/auth/register`,
    login: `${base}/auth/login`,
    loginTwoFactor: `${base}/auth/login/2fa`,
    refresh: `${base}/auth/refresh`,
    logout: `${base}/auth/logout`,
    forgotPassword: `${base}/auth/forgot-password`,
    resetPassword: `${base}/auth/reset-password`,
    changePassword: `${base}/auth/change-password`,
    changeEmail: `${base}/auth/change-email`,
    confirmEmailChange: `${base}/auth/confirm-email-change`,
    deactivateAccount: `${base}/auth/deactivate-account`,
    loginHistory: `${base}/auth/login-history`,
    me: `${base}/me`,
  },
  twoFactor: {
    setup: `${base}/auth/2fa/setup`,
    confirm: `${base}/auth/2fa/confirm`,
    disable: `${base}/auth/2fa/disable`,
    backupCodesStatus: `${base}/auth/2fa/backup-codes/status`,
    regenerateBackupCodes: `${base}/auth/2fa/backup-codes/regenerate`,
    trustedDevices: `${base}/auth/2fa/trusted-devices`,
    revokeTrustedDevice: (id: number) => `${base}/auth/2fa/trusted-devices/${id}`,
  },
  sites: {
    mySites: `${base}/sites`,
    byId: (id: number) => `${base}/sites/${id}`,
    reactivate: (id: number) => `${base}/sites/${id}/reactivate`,
    screenshot: (id: number) => `${base}/sites/${id}/screenshot`,
    confirmPublished: (purchasedSiteId: number) => `${base}/sites/${purchasedSiteId}/confirm-published`,
    topics: `${base}/topics`,
    webmasterSales: `${base}/webmaster/sales`,
    webmasterSalesExport: `${base}/webmaster/sales/export`,
    acceptOrder: (id: number) => `${base}/webmaster/sales/${id}/accept`,
    declineOrder: (id: number) => `${base}/webmaster/sales/${id}/decline`,
    cancelOrder: (id: number) => `${base}/purchased-sites/${id}/cancel`,
    openDispute: (id: number) => `${base}/purchased-sites/${id}/dispute`,
    byProject: (projectId: number) => `${base}/projects/${projectId}/sites`,
    byProjectExport: (projectId: number) => `${base}/projects/${projectId}/sites/export`,
    catalog: `${base}/all-sites`,
    requestPublication: (siteId: number) => `${base}/sites/${siteId}/request-publication`,
    countries: `${base}/countries`,
    verify: (id: number) => `${base}/sites/${id}/verify`,
    reviews: (siteId: number) => `${base}/sites/${siteId}/reviews`,
    events: (purchasedSiteId: number) => `${base}/purchased-sites/${purchasedSiteId}/events`,
  },
  sellers: {
    profile: (id: number) => `${base}/sellers/${id}`,
  },
  savedSearches: {
    mine: `${base}/saved-searches`,
    byId: (id: number) => `${base}/saved-searches/${id}`,
  },
  favorites: {
    mine: `${base}/favorites`,
    ids: `${base}/favorites/ids`,
    byId: (siteId: number) => `${base}/favorites/${siteId}`,
  },
  reviews: {
    create: (purchasedSiteId: number) => `${base}/purchased-sites/${purchasedSiteId}/review`,
    reply: (reviewId: number) => `${base}/reviews/${reviewId}/reply`,
  },
  projects: {
    mine: `${base}/projects`,
    byId: (id: number) => `${base}/projects/${id}`,
  },
  stats: {
    byPageKey: (pageKey: string) => `${base}/stats?page_key=${encodeURIComponent(pageKey)}`,
  },
  messages: {
    byPurchasedSite: (purchasedSiteId: number) => `${base}/purchased-sites/${purchasedSiteId}/messages`,
    attachmentUpload: (purchasedSiteId: number) => `${base}/purchased-sites/${purchasedSiteId}/messages/attachment`,
    attachmentDownload: (purchasedSiteId: number, messageId: number) =>
      `${base}/purchased-sites/${purchasedSiteId}/messages/${messageId}/attachment`,
  },
  conversations: {
    mine: `${base}/conversations`,
    unreadCount: `${base}/conversations/unread-count`,
  },
  support: {
    myThread: `${base}/support/my-thread`,
    myThreadMessages: `${base}/support/my-thread/messages`,
    tickets: `${base}/admin/support/tickets`,
    ticketMessages: (ticketId: number) => `${base}/admin/support/tickets/${ticketId}/messages`,
  },
  admin: {
    dashboard: `${base}/admin/dashboard`,
    users: `${base}/admin/users`,
    banUser: (id: number) => `${base}/admin/users/${id}/ban`,
    setUserRole: (id: number) => `${base}/admin/users/${id}/role`,
    unlockUser: (id: number) => `${base}/admin/users/${id}/unlock`,
    projects: `${base}/admin/projects`,
    transactions: `${base}/admin/transactions`,
    systemLogs: `${base}/admin/system-logs`,
    disputes: `${base}/admin/disputes`,
    resolveDispute: (id: number) => `${base}/admin/disputes/${id}/resolve`,
    withdrawals: `${base}/admin/withdrawals`,
    approveWithdrawal: (id: number) => `${base}/admin/withdrawals/${id}/approve`,
    rejectWithdrawal: (id: number) => `${base}/admin/withdrawals/${id}/reject`,
    reports: {
      orders: `${base}/admin/reports/orders`,
      transactions: `${base}/admin/reports/transactions`,
      users: `${base}/admin/reports/users`,
      withdrawals: `${base}/admin/reports/withdrawals`,
    },
  },
  moderation: {
    pendingSites: `${base}/moderation/sites`,
    approveSite: (id: number) => `${base}/moderation/sites/${id}/approve`,
    rejectSite: (id: number) => `${base}/moderation/sites/${id}/reject`,
    bulkApprove: `${base}/moderation/sites/bulk-approve`,
    bulkReject: `${base}/moderation/sites/bulk-reject`,
    auditLog: `${base}/moderation/audit-log`,
  },
  notifications: {
    mine: `${base}/notifications`,
    unreadCount: `${base}/notifications/unread-count`,
    markAllRead: `${base}/notifications/mark-all-read`,
    preferences: `${base}/notifications/preferences`,
  },
  analytics: {
    mine: `${base}/analytics`,
  },
  wallet: {
    balance: `${base}/wallet`,
    transactions: `${base}/wallet/transactions`,
    topUp: `${base}/wallet/topup`,
    withdraw: `${base}/wallet/withdraw`,
    withdrawals: `${base}/wallet/withdrawals`,
    payoutMethods: `${base}/wallet/payout-methods`,
    payoutMethodById: (id: number) => `${base}/wallet/payout-methods/${id}`,
  },
} as const;
